version: '3'

services:
  core:
    env_file:
      - .env
    build: . # build from home direcory
    command: gunicorn --reload -b 0.0.0.0:${API_PORT} core.app:api
    volumes:
      - .:/src/ # sync local with container
    ports:
      - 8313:8313
